
networks:
  offeristanet:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
services:
  producer-service:
    build: ./producer
#    ports:
#      - "8081:8081"
    depends_on:
      - consumer-service
    networks:
        offeristanet:
         ipv4_address: 172.20.0.2

  consumer-service:
    build: ./consumer
    networks:
      offeristanet:
        ipv4_address: 172.20.0.3
#    ports:
#      - "8082:8082"